<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>9.2 交差項 | マーケティングリサーチ講義ノート</title>
  <meta name="description" content="9.2 交差項 | マーケティングリサーチ講義ノート" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="9.2 交差項 | マーケティングリサーチ講義ノート" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="https://github.com/tak-tag/MktRes_Lecture.git" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="9.2 交差項 | マーケティングリサーチ講義ノート" />
  
  
  

<meta name="author" content="Takumi Tagashira" />


<meta name="date" content="2024-03-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ダミー変数.html"/>
<link rel="next" href="係数比較.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Marketing Research Lecture Note</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> はじめに（本資料について）</a></li>
<li class="chapter" data-level="2" data-path="rusage.html"><a href="rusage.html"><i class="fa fa-check"></i><b>2</b> R と R studioに慣れる</a>
<ul>
<li class="chapter" data-level="2.1" data-path="posit-cloudを始める.html"><a href="posit-cloudを始める.html"><i class="fa fa-check"></i><b>2.1</b> Posit cloudを始める</a></li>
<li class="chapter" data-level="2.2" data-path="補足r-studio-デスクトップ版の利用.html"><a href="補足r-studio-デスクトップ版の利用.html"><i class="fa fa-check"></i><b>2.2</b> （補足）R studio デスクトップ版の利用</a></li>
<li class="chapter" data-level="2.3" data-path="補足デスクトップ版の利用とプロジェクト機能.html"><a href="補足デスクトップ版の利用とプロジェクト機能.html"><i class="fa fa-check"></i><b>2.3</b> （補足）デスクトップ版の利用とプロジェクト機能</a></li>
<li class="chapter" data-level="2.4" data-path="rの基本操作.html"><a href="rの基本操作.html"><i class="fa fa-check"></i><b>2.4</b> Rの基本操作</a></li>
<li class="chapter" data-level="2.5" data-path="r-スクリプトのすゝめ.html"><a href="r-スクリプトのすゝめ.html"><i class="fa fa-check"></i><b>2.5</b> R スクリプトのすゝめ</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="r-スクリプトのすゝめ.html"><a href="r-スクリプトのすゝめ.html#rスクリプトを書く"><i class="fa fa-check"></i><b>2.5.1</b> Rスクリプトを書く</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="本章のまとめ.html"><a href="本章のまとめ.html"><i class="fa fa-check"></i><b>2.6</b> 本章のまとめ</a></li>
<li class="chapter" data-level="2.7" data-path="参考文献.html"><a href="参考文献.html"><i class="fa fa-check"></i><b>2.7</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="design.html"><a href="design.html"><i class="fa fa-check"></i><b>3</b> リサーチデザイン</a>
<ul>
<li class="chapter" data-level="3.1" data-path="マーケティング実務とリサーチ.html"><a href="マーケティング実務とリサーチ.html"><i class="fa fa-check"></i><b>3.1</b> マーケティング実務とリサーチ</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="マーケティング実務とリサーチ.html"><a href="マーケティング実務とリサーチ.html#実務とリサーチの異なる視点"><i class="fa fa-check"></i><b>3.1.1</b> 実務とリサーチの異なる視点</a></li>
<li class="chapter" data-level="3.1.2" data-path="マーケティング実務とリサーチ.html"><a href="マーケティング実務とリサーチ.html#実務とリサーチの分離"><i class="fa fa-check"></i><b>3.1.2</b> 実務とリサーチの分離</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="リサーチデザインと論文の構成.html"><a href="リサーチデザインと論文の構成.html"><i class="fa fa-check"></i><b>3.2</b> リサーチデザインと論文の構成</a></li>
<li class="chapter" data-level="3.3" data-path="question.html"><a href="question.html"><i class="fa fa-check"></i><b>3.3</b> 研究課題（問い）の設定</a></li>
<li class="chapter" data-level="3.4" data-path="問題と分析をつなげる仮説の提示.html"><a href="問題と分析をつなげる仮説の提示.html"><i class="fa fa-check"></i><b>3.4</b> 問題と分析をつなげる仮説の提示</a></li>
<li class="chapter" data-level="3.5" data-path="学術的研究のための留意点.html"><a href="学術的研究のための留意点.html"><i class="fa fa-check"></i><b>3.5</b> 学術的研究のための留意点</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="学術的研究のための留意点.html"><a href="学術的研究のための留意点.html#マーケティング研究と科学哲学"><i class="fa fa-check"></i><b>3.5.1</b> マーケティング研究と科学哲学</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="研究における理論の利用と精緻化.html"><a href="研究における理論の利用と精緻化.html"><i class="fa fa-check"></i><b>3.6</b> 研究における理論の利用と精緻化</a></li>
<li class="chapter" data-level="3.7" data-path="参考文献-1.html"><a href="参考文献-1.html"><i class="fa fa-check"></i><b>3.7</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="survey.html"><a href="survey.html"><i class="fa fa-check"></i><b>4</b> データの種類とアンケートデザイン</a>
<ul>
<li class="chapter" data-level="4.1" data-path="記述的リサーチデザイン.html"><a href="記述的リサーチデザイン.html"><i class="fa fa-check"></i><b>4.1</b> 記述的リサーチデザイン</a></li>
<li class="chapter" data-level="4.2" data-path="アンケート設計.html"><a href="アンケート設計.html"><i class="fa fa-check"></i><b>4.2</b> アンケート設計</a></li>
<li class="chapter" data-level="4.3" data-path="質問におけるワーディング.html"><a href="質問におけるワーディング.html"><i class="fa fa-check"></i><b>4.3</b> 質問におけるワーディング</a></li>
<li class="chapter" data-level="4.4" data-path="アンケートデザイン.html"><a href="アンケートデザイン.html"><i class="fa fa-check"></i><b>4.4</b> アンケートデザイン</a></li>
<li class="chapter" data-level="4.5" data-path="参考文献-2.html"><a href="参考文献-2.html"><i class="fa fa-check"></i><b>4.5</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="handling.html"><a href="handling.html"><i class="fa fa-check"></i><b>5</b> データ処理と顧客関係管理（CRM）</a>
<ul>
<li class="chapter" data-level="5.1" data-path="データの読み込み.html"><a href="データの読み込み.html"><i class="fa fa-check"></i><b>5.1</b> データの読み込み</a></li>
<li class="chapter" data-level="5.2" data-path="データの整形.html"><a href="データの整形.html"><i class="fa fa-check"></i><b>5.2</b> データの整形</a></li>
<li class="chapter" data-level="5.3" data-path="統計的検定を用いない顧客分析.html"><a href="統計的検定を用いない顧客分析.html"><i class="fa fa-check"></i><b>5.3</b> 統計的検定を用いない顧客分析</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="統計的検定を用いない顧客分析.html"><a href="統計的検定を用いない顧客分析.html#データの構造変化とソート"><i class="fa fa-check"></i><b>5.3.1</b> データの構造変化とソート</a></li>
<li class="chapter" data-level="5.3.2" data-path="統計的検定を用いない顧客分析.html"><a href="統計的検定を用いない顧客分析.html#データ結合"><i class="fa fa-check"></i><b>5.3.2</b> データ結合</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="おまけ-wide型とlong型データセット.html"><a href="おまけ-wide型とlong型データセット.html"><i class="fa fa-check"></i><b>5.4</b> (おまけ) Wide型とLong型データセット</a></li>
<li class="chapter" data-level="5.5" data-path="参考文献-3.html"><a href="参考文献-3.html"><i class="fa fa-check"></i><b>5.5</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="データの要約と可視化.html"><a href="データの要約と可視化.html"><i class="fa fa-check"></i><b>6</b> データの要約と可視化</a>
<ul>
<li class="chapter" data-level="6.1" data-path="記述統計.html"><a href="記述統計.html"><i class="fa fa-check"></i><b>6.1</b> 記述統計</a></li>
<li class="chapter" data-level="6.2" data-path="カテゴリ変数の要約.html"><a href="カテゴリ変数の要約.html"><i class="fa fa-check"></i><b>6.2</b> カテゴリ変数の要約</a></li>
<li class="chapter" data-level="6.3" data-path="データの可視化.html"><a href="データの可視化.html"><i class="fa fa-check"></i><b>6.3</b> データの可視化</a></li>
<li class="chapter" data-level="6.4" data-path="二変数間の関係の要約.html"><a href="二変数間の関係の要約.html"><i class="fa fa-check"></i><b>6.4</b> 二変数間の関係の要約</a></li>
<li class="chapter" data-level="6.5" data-path="参考文献-4.html"><a href="参考文献-4.html"><i class="fa fa-check"></i><b>6.5</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="test.html"><a href="test.html"><i class="fa fa-check"></i><b>7</b> 基礎統計学復習</a>
<ul>
<li class="chapter" data-level="7.1" data-path="確率モデル期待値と分散.html"><a href="確率モデル期待値と分散.html"><i class="fa fa-check"></i><b>7.1</b> 確率モデル、期待値と分散</a></li>
<li class="chapter" data-level="7.2" data-path="統計的推測.html"><a href="統計的推測.html"><i class="fa fa-check"></i><b>7.2</b> 統計的推測</a></li>
<li class="chapter" data-level="7.3" data-path="点推定.html"><a href="点推定.html"><i class="fa fa-check"></i><b>7.3</b> 点推定</a></li>
<li class="chapter" data-level="7.4" data-path="推定量もまた確率変数.html"><a href="推定量もまた確率変数.html"><i class="fa fa-check"></i><b>7.4</b> 推定量もまた確率変数</a></li>
<li class="chapter" data-level="7.5" data-path="補足いくつかの確率分布の関係性.html"><a href="補足いくつかの確率分布の関係性.html"><i class="fa fa-check"></i><b>7.5</b> 補足（いくつかの確率分布の関係性）</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="補足いくつかの確率分布の関係性.html"><a href="補足いくつかの確率分布の関係性.html#正規分布"><i class="fa fa-check"></i><b>7.5.1</b> 正規分布</a></li>
<li class="chapter" data-level="7.5.2" data-path="補足いくつかの確率分布の関係性.html"><a href="補足いくつかの確率分布の関係性.html#カイ二乗分布"><i class="fa fa-check"></i><b>7.5.2</b> カイ二乗分布</a></li>
<li class="chapter" data-level="7.5.3" data-path="補足いくつかの確率分布の関係性.html"><a href="補足いくつかの確率分布の関係性.html#t分布"><i class="fa fa-check"></i><b>7.5.3</b> t分布</a></li>
<li class="chapter" data-level="7.5.4" data-path="補足いくつかの確率分布の関係性.html"><a href="補足いくつかの確率分布の関係性.html#f分布"><i class="fa fa-check"></i><b>7.5.4</b> F分布</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="区間推定.html"><a href="区間推定.html"><i class="fa fa-check"></i><b>7.6</b> 区間推定</a></li>
<li class="chapter" data-level="7.7" data-path="統計的仮説検定.html"><a href="統計的仮説検定.html"><i class="fa fa-check"></i><b>7.7</b> 統計的仮説検定</a></li>
<li class="chapter" data-level="7.8" data-path="平均値に関するその他の検定.html"><a href="平均値に関するその他の検定.html"><i class="fa fa-check"></i><b>7.8</b> 平均値に関するその他の検定</a></li>
<li class="chapter" data-level="7.9" data-path="分散分析.html"><a href="分散分析.html"><i class="fa fa-check"></i><b>7.9</b> 分散分析</a></li>
<li class="chapter" data-level="7.10" data-path="参考文献-5.html"><a href="参考文献-5.html"><i class="fa fa-check"></i><b>7.10</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="regintro.html"><a href="regintro.html"><i class="fa fa-check"></i><b>8</b> 回帰分析</a>
<ul>
<li class="chapter" data-level="8.1" data-path="回帰モデル概要.html"><a href="回帰モデル概要.html"><i class="fa fa-check"></i><b>8.1</b> 回帰モデル概要</a></li>
<li class="chapter" data-level="8.2" data-path="回帰分析における推定と検定.html"><a href="回帰分析における推定と検定.html"><i class="fa fa-check"></i><b>8.2</b> 回帰分析における推定と検定</a></li>
<li class="chapter" data-level="8.3" data-path="重回帰モデル1.html"><a href="重回帰モデル1.html"><i class="fa fa-check"></i><b>8.3</b> 重回帰モデル1</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="重回帰モデル1.html"><a href="重回帰モデル1.html#重回帰モデル概要"><i class="fa fa-check"></i><b>8.3.1</b> 重回帰モデル概要</a></li>
<li class="chapter" data-level="8.3.2" data-path="重回帰モデル1.html"><a href="重回帰モデル1.html#重回帰分析におけるモデル適合度"><i class="fa fa-check"></i><b>8.3.2</b> 重回帰分析におけるモデル適合度</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="重回帰モデル2.html"><a href="重回帰モデル2.html"><i class="fa fa-check"></i><b>8.4</b> 重回帰モデル2</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="重回帰モデル2.html"><a href="重回帰モデル2.html#回帰係数の解釈"><i class="fa fa-check"></i><b>8.4.1</b> 回帰係数の解釈</a></li>
<li class="chapter" data-level="8.4.2" data-path="重回帰モデル2.html"><a href="重回帰モデル2.html#重回帰モデルにおける変数選択"><i class="fa fa-check"></i><b>8.4.2</b> 重回帰モデルにおける変数選択</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="参考文献-6.html"><a href="参考文献-6.html"><i class="fa fa-check"></i><b>8.5</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="regtechnic.html"><a href="regtechnic.html"><i class="fa fa-check"></i><b>9</b> 回帰分析上の工夫紹介</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ダミー変数.html"><a href="ダミー変数.html"><i class="fa fa-check"></i><b>9.1</b> ダミー変数</a></li>
<li class="chapter" data-level="9.2" data-path="交差項.html"><a href="交差項.html"><i class="fa fa-check"></i><b>9.2</b> 交差項</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="交差項.html"><a href="交差項.html#傾きダミー"><i class="fa fa-check"></i><b>9.2.1</b> 傾きダミー</a></li>
<li class="chapter" data-level="9.2.2" data-path="交差項.html"><a href="交差項.html#量的変数同士の交差項"><i class="fa fa-check"></i><b>9.2.2</b> 量的変数同士の交差項</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="係数比較.html"><a href="係数比較.html"><i class="fa fa-check"></i><b>9.3</b> 係数比較</a></li>
<li class="chapter" data-level="9.4" data-path="対数線形.html"><a href="対数線形.html"><i class="fa fa-check"></i><b>9.4</b> 対数線形</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="対数線形.html"><a href="対数線形.html#需要の価格弾力性追加説明"><i class="fa fa-check"></i><b>9.4.1</b> 需要の価格弾力性追加説明</a></li>
<li class="chapter" data-level="9.4.2" data-path="対数線形.html"><a href="対数線形.html#対数線形の推定と検定"><i class="fa fa-check"></i><b>9.4.2</b> 対数線形の推定と検定</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="おまけ分析結果のまとめ出力上の工夫.html"><a href="おまけ分析結果のまとめ出力上の工夫.html"><i class="fa fa-check"></i><b>9.5</b> （おまけ）分析結果のまとめ・出力上の工夫</a></li>
<li class="chapter" data-level="9.6" data-path="参考文献-7.html"><a href="参考文献-7.html"><i class="fa fa-check"></i><b>9.6</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="cluster.html"><a href="cluster.html"><i class="fa fa-check"></i><b>10</b> セグメントとクラスター分析</a>
<ul>
<li class="chapter" data-level="10.1" data-path="セグメンテーションとマーケティング意思決定.html"><a href="セグメンテーションとマーケティング意思決定.html"><i class="fa fa-check"></i><b>10.1</b> セグメンテーションとマーケティング意思決定</a></li>
<li class="chapter" data-level="10.2" data-path="stpその後.html"><a href="stpその後.html"><i class="fa fa-check"></i><b>10.2</b> STPその後</a></li>
<li class="chapter" data-level="10.3" data-path="セグメンテーションの実行とクラスター分析.html"><a href="セグメンテーションの実行とクラスター分析.html"><i class="fa fa-check"></i><b>10.3</b> セグメンテーションの実行とクラスター分析</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="セグメンテーションの実行とクラスター分析.html"><a href="セグメンテーションの実行とクラスター分析.html#Hier"><i class="fa fa-check"></i><b>10.3.1</b> 階層的クラスター分析</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="k-means.html"><a href="k-means.html"><i class="fa fa-check"></i><b>10.4</b> 非階層的クラスター分析：K-means法</a></li>
<li class="chapter" data-level="10.5" data-path="rによるクラスター分析の実行.html"><a href="rによるクラスター分析の実行.html"><i class="fa fa-check"></i><b>10.5</b> Rによるクラスター分析の実行</a></li>
<li class="chapter" data-level="10.6" data-path="参考文献-8.html"><a href="参考文献-8.html"><i class="fa fa-check"></i><b>10.6</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="factor.html"><a href="factor.html"><i class="fa fa-check"></i><b>11</b> 知覚マップと因子分析</a>
<ul>
<li class="chapter" data-level="11.1" data-path="ポジショニングと知覚マップ概要.html"><a href="ポジショニングと知覚マップ概要.html"><i class="fa fa-check"></i><b>11.1</b> ポジショニングと知覚マップ概要</a></li>
<li class="chapter" data-level="11.2" data-path="因子分析概要.html"><a href="因子分析概要.html"><i class="fa fa-check"></i><b>11.2</b> 因子分析概要</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="因子分析概要.html"><a href="因子分析概要.html#因子分析の概要とモデルの構造"><i class="fa fa-check"></i><b>11.2.1</b> 因子分析の概要とモデルの構造</a></li>
<li class="chapter" data-level="11.2.2" data-path="因子分析概要.html"><a href="因子分析概要.html#因子モデル"><i class="fa fa-check"></i><b>11.2.2</b> 2因子モデル</a></li>
<li class="chapter" data-level="11.2.3" data-path="因子分析概要.html"><a href="因子分析概要.html#因子スコア"><i class="fa fa-check"></i><b>11.2.3</b> 因子スコア</a></li>
<li class="chapter" data-level="11.2.4" data-path="因子分析概要.html"><a href="因子分析概要.html#小括"><i class="fa fa-check"></i><b>11.2.4</b> 小括</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="rによる因子分析の実行.html"><a href="rによる因子分析の実行.html"><i class="fa fa-check"></i><b>11.3</b> Rによる因子分析の実行</a></li>
<li class="chapter" data-level="11.4" data-path="アンケートデータと知覚マップ.html"><a href="アンケートデータと知覚マップ.html"><i class="fa fa-check"></i><b>11.4</b> アンケートデータと知覚マップ</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="アンケートデータと知覚マップ.html"><a href="アンケートデータと知覚マップ.html#データ構造の変更"><i class="fa fa-check"></i><b>11.4.1</b> データ構造の変更</a></li>
<li class="chapter" data-level="11.4.2" data-path="アンケートデータと知覚マップ.html"><a href="アンケートデータと知覚マップ.html#因子分析の実行"><i class="fa fa-check"></i><b>11.4.2</b> 因子分析の実行</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="参考文献-9.html"><a href="参考文献-9.html"><i class="fa fa-check"></i><b>11.5</b> 参考文献</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="psm.html"><a href="psm.html"><i class="fa fa-check"></i><b>12</b> 価格感度測定 (PSM)</a>
<ul>
<li class="chapter" data-level="12.1" data-path="psmrunning.html"><a href="psmrunning.html"><i class="fa fa-check"></i><b>12.1</b> PSMの実行と結果</a></li>
<li class="chapter" data-level="12.2" data-path="price_concept.html"><a href="price_concept.html"><i class="fa fa-check"></i><b>12.2</b> マーケティングにおける価格概念</a></li>
<li class="chapter" data-level="12.3" data-path="psmに関する既存研究.html"><a href="psmに関する既存研究.html"><i class="fa fa-check"></i><b>12.3</b> PSMに関する既存研究</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="psmに関する既存研究.html"><a href="psmに関する既存研究.html#受容価格に関する知見"><i class="fa fa-check"></i><b>12.3.1</b> 受容価格に関する知見</a></li>
<li class="chapter" data-level="12.3.2" data-path="psmに関する既存研究.html"><a href="psmに関する既存研究.html#内的参照価格に関する知見"><i class="fa fa-check"></i><b>12.3.2</b> 内的参照価格に関する知見</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="受容価格帯と内的参照価格帯の応用とpsm.html"><a href="受容価格帯と内的参照価格帯の応用とpsm.html"><i class="fa fa-check"></i><b>12.4</b> 受容価格帯と内的参照価格帯の応用とPSM</a></li>
<li class="chapter" data-level="12.5" data-path="集計方法に関する注意点.html"><a href="集計方法に関する注意点.html"><i class="fa fa-check"></i><b>12.5</b> 集計方法に関する注意点</a></li>
<li class="chapter" data-level="12.6" data-path="参考文献-10.html"><a href="参考文献-10.html"><i class="fa fa-check"></i><b>12.6</b> 参考文献</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">マーケティングリサーチ講義ノート</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="交差項" class="section level2 hasAnchor" number="9.2">
<h2><span class="header-section-number">9.2</span> 交差項<a href="交差項.html#交差項" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>マーケティングに関する研究では、ある説明変数の被説明変数に与える影響が、別の説明変数に影響を受ける形で変化することを捉えることも多い。このような変数間の関係に影響するような効果を調整効果（moderating effect）もしくは相互作用効果（interaction effect）と言い、以下のような図で示されることが多い。</p>
<div class="float">
<img src="reg/moderate.png" style="width:70.0%" alt="ダミー変数関係図" />
<div class="figcaption">ダミー変数関係図</div>
</div>
<p>上の図では、メインの説明変数と調整変数が存在するかのように見えるが、分析に置いてはどちらか一方をメインと扱うことはなく、<em>X</em>と<em>Z</em>をかけ合わせた交差項を含めたモデルを分析する。なお、調整効果もしくは相互作用効果の分析ではダミー変数もしくは量的変数のどちらも用いることができる。</p>
<div class="float">
<img src="reg/moderate2.png" style="width:70.0%" alt="交差項概念図" />
<div class="figcaption">交差項概念図</div>
</div>
<p>回帰モデルにおける交差項の利用には、以下の点に注意が必要である。</p>
<ol style="list-style-type: decimal">
<li>交差項には、条件付き効果に関する作業仮説を論じる必要がある。</li>
</ol>
<ul>
<li>例、XがYに与える影響は、Zの値に応じて変化する。</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>交差項を含むモデルには交差項を構成する二つの変数も含める。</li>
</ol>
<ul>
<li>推定モデル上、どちらか一方がメインかのような特定化は行わない。</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>交差項を構成する二つの変数の係数を従来の回帰分析結果と同じように解釈してはいけない。</li>
</ol>
<ul>
<li>説明変数独立項の係数の意味について注意が必要。</li>
</ul>
<div id="傾きダミー" class="section level3 hasAnchor" number="9.2.1">
<h3><span class="header-section-number">9.2.1</span> 傾きダミー<a href="交差項.html#傾きダミー" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>先述の注意点について、具体例を見ながら確認していく。まず、量的変数とダミー変数の交差項について考える。ダミー変数と量的変数の交差項を作ることによって、傾きがグループによって変わるか否かを捉えることができる。交差項を含む回帰モデルは以下のように示される。</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i+\beta_2D_i+\beta_3(x_i\times D_i)+u_i
\]</span></p>
<p><span class="math inline">\(\small x_i\)</span> が <span class="math inline">\(\small y_i\)</span> に与える影響を <span class="math inline">\(\small \Delta y_i/\Delta x_i\)</span> とすると、それぞれ以下のように示される。</p>
<p><span class="math display">\[
\begin{cases}
D_i=1\Rightarrow &amp; \frac{\Delta y_i}{\Delta x_i}=\beta_1+\beta_3\\
D_i=0\Rightarrow &amp; \frac{\Delta y_i}{\Delta x_i}=\beta_1
\end{cases}
\]</span>
つまり、<span class="math inline">\(\small x\)</span> が <span class="math inline">\(\small y\)</span> に与える影響（傾き）が、<span class="math inline">\(\small \beta_3\)</span> の分だけ、ダミー変数のカテゴリーによって変化することが伺える。<span class="math inline">\(\small \beta_1\)</span> は <span class="math inline">\(\small D=0\)</span> の際の <em>x</em> の効果であり、 <span class="math inline">\(\small D=1\)</span> の際の効果は、<span class="math inline">\(\small \beta_1+\beta_3\)</span> で表される。 そのため、このようなダミー変数の使い方を「傾きダミー（Slope dummy）」と呼ぶことも多い。</p>
<p>先程の firmdara19 にこの分析モデルを適応してみる。Rにおける交差項の導入は、<code>lm(y ~ x * d)</code> のように指定すれば、<em>x</em>と<em>d</em>の交差項とそれぞれの独立項を自動でモデルに含めてくれる。</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="交差項.html#cb211-1" tabindex="-1"></a>fit.d3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(op <span class="sc">~</span>  mkexp <span class="sc">*</span> retail, <span class="at">data =</span> firmdata19)</span>
<span id="cb211-2"><a href="交差項.html#cb211-2" tabindex="-1"></a><span class="fu">summary</span>(fit.d3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = op ~ mkexp * retail, data = firmdata19)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.096735 -0.028600 -0.005523  0.018005  0.258568 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   0.108430   0.009217  11.764  &lt; 2e-16 ***
## mkexp        -0.105662   0.027505  -3.842 0.000183 ***
## retail       -0.088147   0.023231  -3.794 0.000218 ***
## mkexp:retail  0.191432   0.063025   3.037 0.002837 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.05305 on 143 degrees of freedom
## Multiple R-squared:  0.1585, Adjusted R-squared:  0.1409 
## F-statistic: 8.979 on 3 and 143 DF,  p-value: 1.73e-05</code></pre>
<p>分析の結果、マーケティング支出と小売ダミーは負に有意である一方で、両変数の交差項（`<code>mkexp:retail</code>）は正に有意であることが示された。このとき、<code>mkexp</code> の単独項は、<code>retail</code> が0のとき、つまりその他グループにおけるマーケティング支出と利益率の関係を示しており、それが負に有意であると理解できる。そして、<code>mkexp:retail</code> の項が正に有意であることから、その他グループの傾きと、小売グループの傾きは有意に異なることが伺える。もう少し詳細にこの結果を整理すると、本分析による利益率の予測値 <span class="math inline">\(\hat{y}\)</span>は以下のように示すことができる。</p>
<p><span class="math display">\[
\hat{y}_i = 0.108430 - 0.105662\text{mkexp}_i - 0.088147\text{retail}_i + 0.191432\text{mkexp}_i * \text{retail}_i
\]</span></p>
<p><span class="math display">\[
\begin{cases}
\text{Retail}: &amp;\hat{y}_i = 0.020283 + 0.08577\text{mkexp}_i\\
\text{Others}: &amp;\hat{y}_i = 0.108430 - 0.105662\text{mkexp}_i
\end{cases}
\]</span></p>
<p>交差項を用いた分析を実行する場合、分析結果をより詳細に理解するため、結果を図示化することが大切になる。具体的には以下のように、分析結果からカテゴリ別に予測値をそれぞれ計算し、図示化することで、含意を得ることができる。ここでは、<code>sjPlot</code>というパッケージの <code>plot_model()</code> 関数を用いて、分析結果に基づく被説明変数の予測値を図示化する。まず、パッケージをインストールして欲しい。</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="交差項.html#cb213-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;sjPlot&quot;</span>)</span></code></pre></div>
<p>今回の図示化のために、<code>plot_model()</code> 関数内では、<code>type = "pred"</code> と引数を指定した上で、<code>terms</code> において着目する変数名を特定する。また、この関数では、ggplot2のように、図示化に関する凡例や軸ラベルなどの様々な情報を書き足していくことができる。</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="交差項.html#cb214-1" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb214-2"><a href="交差項.html#cb214-2" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">plot_model</span>(fit.d3, <span class="at">type =</span> <span class="st">&quot;pred&quot;</span>, <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">&quot;mkexp&quot;</span>,<span class="st">&quot;retail&quot;</span>), <span class="at">ci.lvl =</span> .<span class="dv">95</span>) <span class="sc">+</span></span>
<span id="cb214-3"><a href="交差項.html#cb214-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Slope Analysis&quot;</span>,</span>
<span id="cb214-4"><a href="交差項.html#cb214-4" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;(Predicted Values of Profitability with 95% Confdence Intervals)&quot;</span>,</span>
<span id="cb214-5"><a href="交差項.html#cb214-5" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Marketing Expense&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Profitability&quot;</span>) <span class="sc">+</span></span>
<span id="cb214-6"><a href="交差項.html#cb214-6" tabindex="-1"></a>  <span class="fu">scale_color_discrete</span>(<span class="at">name =</span> <span class="st">&quot;Retail Dummy&quot;</span>)</span>
<span id="cb214-7"><a href="交差項.html#cb214-7" tabindex="-1"></a>pred</span></code></pre></div>
<p><img src="mktres_lecture_files/figure-html/slopeanalysis-1.png" width="672" /></p>
<p>分析の結果、小売企業においてはマーケティング支出と利益率の関係は右上がりである一方で、その他の企業では右下がりである。回帰分析における交差項の係数がこの傾きの違いを示している。また、実線を比較すると マーケティング支出が 0.5 辺りを境に小売企業の利益率の予測値のほうがその他グループよりも高くなっているように見える<a href="#fn12" class="footnote-ref" id="fnref12"><sup>12</sup></a>。しかしながら、両直線の95%信頼区間は重なっており、統計的に有意な差があるとは言えない。そのため、マーケティング支出が高いとき、小売企業の利益率（の予測値）のほうが有意に高いとは言えない。</p>
</div>
<div id="量的変数同士の交差項" class="section level3 hasAnchor" number="9.2.2">
<h3><span class="header-section-number">9.2.2</span> 量的変数同士の交差項<a href="交差項.html#量的変数同士の交差項" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>交差項を用いた分析は量的変数同士にも応用できる。しかしながら、交差項を用いた分析結果の解釈には注意が必要であり、分析の実行においても工夫が求められる。量的変数同士の交差項モデルとして、以下の回帰式を考える。</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i+\beta_2z_i+\beta_3(x_i\times z_i)+u_i
\]</span></p>
<p>上記における <em>x</em> と <em>z</em> はどちらも量的変数であり、<em>x</em> が <em>y</em> に与えるパーシャル効果は、以下のように表すことができる。</p>
<p><span class="math display">\[
\frac{\Delta y_i}{\Delta x_i}=\beta_1+\beta_3z_i
\]</span>
同様に、<em>z</em> が <em>y</em> に与えるパーシャル効果は、</p>
<p><span class="math display">\[
\frac{\Delta y_i}{\Delta z_i}=\beta_2+\beta_3x_i
\]</span>
となる。したがって、<em>x</em> と <em>z</em> が <em>y</em> に与える影響は、互いに依存しあっていることがわかる。上式の <span class="math inline">\(\small \beta_3\)</span> は調整効果や相互作用効果と呼ばれる。</p>
<p>交差項を用いた回帰モデルでは、説明変数の独立項に関する解釈に注意が必要となる。例えば上式の <span class="math inline">\(\small \beta_1\)</span>（<span class="math inline">\(\small \beta_2\)</span>）はどのような条件で <em>x</em>（<em>z</em>）が <em>y</em> に与える影響だと解釈できるだろうか。例えば、上記のモデルにおける <em>y</em> が体重、 <em>x</em> と <em>z</em> がそれぞれ筋肉量と身長だったとする。このとき、筋肉量が体重に与える影響は、
<span class="math display">\[
\frac{\Delta y_i}{\Delta x_i}=\beta_1+\beta_3z_i
\]</span></p>
<p>であり、<span class="math inline">\(\small \beta_1\)</span> は「身長（<em>z</em>）が0」という条件下で筋肉量が体重に与える影響を表している。しかしながら、身長が0のときという非現実的な条件下での結果は、我々にとって解釈が難しく、また情報としても有益でないかもしれない。この問題への対策のひとつが「平均値での中心化（mean-centering）」である。これは、交差項に用いる説明変数に関して、平均からの偏差を用いる方法である。中心化された変数による交差項モデルは以下のように示される。</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 (x_i-\bar{x})+\beta_2(z_i-\bar{z})+\beta_3(x_i-\bar{x})\times (z_i-\bar{z})+u_i
\]</span></p>
<p>これにより、<em>x</em> の効果は以下のように示される。</p>
<p><span class="math display">\[
\frac{\Delta y_i}{\Delta x_i}=\beta_1+\beta_3(z_i-\bar{z})
\]</span></p>
<p>そのため、中心化されたモデルにおける<span class="math inline">\(\small \beta_1\)</span> は、<span class="math inline">\(\small z_i-\bar{z}=0\)</span>、つまり「<em>z</em> が平均値」の際の、<em>x</em> 効果だと解釈できる。また、平均値以外の値を用いた中心化も当然可能であるため、研究・実務上関心の強い値（何らかの閾値など）がある場合には、それを基準とした中心化もできる。</p>
<p>ここで、量的変数を用いた交差項モデルをRで分析する。分析の実行方法は、前節の傾きダミーと同様である。ここでは、“headphone07.csv” という、ある年のヘッドフォン製品の売上を捉えたデータセット（人工架空データ）を用いる。このデータは、以下の変数を含んでいる。</p>
<ul>
<li>売上（百万円）</li>
<li>プロモーション投資額（百万円）</li>
<li>R&amp;D投資額（百万円）</li>
</ul>
<p>このデータセットに対して、本分析ではR&amp;Dによって向上する（と仮定する）製品品質とプロモーションの相互作用が売上に与える影響を分析する。具体的には、たとえ良いものを作っても、きちんとその情報を消費者に伝達しないといけないのではないかという課題を捉える。そのため本分析を通じて、製品品質への投資（R&amp;D投資）が売上に与える影響が、プロモーション量に応じて変化するのではないかという研究課題に答える。まず以下のようにデータを読み込み、データフレームを確認する。</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="交差項.html#cb215-1" tabindex="-1"></a>Headphone07 <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">&quot;data/headphone07.csv&quot;</span>, <span class="at">na =</span> <span class="st">&quot;.&quot;</span>)</span>
<span id="cb215-2"><a href="交差項.html#cb215-2" tabindex="-1"></a></span>
<span id="cb215-3"><a href="交差項.html#cb215-3" tabindex="-1"></a><span class="co">#データフレームの確認</span></span>
<span id="cb215-4"><a href="交差項.html#cb215-4" tabindex="-1"></a><span class="fu">glimpse</span>(Headphone07)</span></code></pre></div>
<pre><code>## Rows: 221
## Columns: 4
## $ ID        &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…
## $ sales     &lt;dbl&gt; 118.8377, 548.6312, 197.3075, 104.2657, 748.8251, 947.8850, …
## $ rd        &lt;dbl&gt; 404.0893, 252.1270, 444.3374, 407.5876, 841.7605, 336.8744, …
## $ promotion &lt;dbl&gt; 75.63163, 102.74572, 97.98040, 83.46613, 105.69250, 80.17476…</code></pre>
<p>このデータに対して、まずは以下の通り中心化していない変数を用いて分析を行う。</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="交差項.html#cb217-1" tabindex="-1"></a>fit_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> rd<span class="sc">*</span>promotion, <span class="at">data =</span> Headphone07)</span>
<span id="cb217-2"><a href="交差項.html#cb217-2" tabindex="-1"></a><span class="fu">summary</span>(fit_int)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sales ~ rd * promotion, data = Headphone07)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -46.522 -12.861  -0.638  13.578  70.667 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   2.033e+04  1.090e+02   186.5   &lt;2e-16 ***
## rd           -5.187e+01  2.844e-01  -182.4   &lt;2e-16 ***
## promotion    -1.914e+02  1.052e+00  -181.9   &lt;2e-16 ***
## rd:promotion  4.979e-01  2.730e-03   182.4   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 20.55 on 217 degrees of freedom
## Multiple R-squared:  0.9935, Adjusted R-squared:  0.9934 
## F-statistic: 1.111e+04 on 3 and 217 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>分析の結果、rdとpromotion の交差項は正に有意だが、どちらの独立項も負に有意であった。また、先述の通りこれらの独立項の係数は、もう一方の変数が0のときのそれぞれの効果を表しており、現実的には解釈が難しい結果になっている。したがって、以下の様に中心化変数を作成し、回帰分析を実行する。</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="交差項.html#cb219-1" tabindex="-1"></a>Headphone07 <span class="ot">&lt;-</span> Headphone07 <span class="sc">%&gt;%</span> </span>
<span id="cb219-2"><a href="交差項.html#cb219-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">promotion_c =</span> promotion <span class="sc">-</span> <span class="fu">mean</span>(promotion, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb219-3"><a href="交差項.html#cb219-3" tabindex="-1"></a>         <span class="at">rd_c =</span> rd <span class="sc">-</span> <span class="fu">mean</span>(rd, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb219-4"><a href="交差項.html#cb219-4" tabindex="-1"></a></span>
<span id="cb219-5"><a href="交差項.html#cb219-5" tabindex="-1"></a>fit_int_c <span class="ot">&lt;-</span> <span class="fu">lm</span>(sales <span class="sc">~</span> rd_c<span class="sc">*</span>promotion_c , <span class="at">data =</span> Headphone07)</span>
<span id="cb219-6"><a href="交差項.html#cb219-6" tabindex="-1"></a><span class="fu">summary</span>(fit_int_c)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sales ~ rd_c * promotion_c, data = Headphone07)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -46.522 -12.861  -0.638  13.578  70.667 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      382.27812    1.51459  252.40   &lt;2e-16 ***
## rd_c              -0.91767    0.01196  -76.75   &lt;2e-16 ***
## promotion_c        0.69039    0.03972   17.38   &lt;2e-16 ***
## rd_c:promotion_c   0.49792    0.00273  182.37   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 20.55 on 217 degrees of freedom
## Multiple R-squared:  0.9935, Adjusted R-squared:  0.9934 
## F-statistic: 1.111e+04 on 3 and 217 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>分析の結果、交差項の結果については非中心化モデルと同じであることが伺える。一方で独立項については、rdは負に、promotionは正に有意であることが明らかになった。つまり、プロモーションが平均値である場合、rdにコストを掛けても売上には繋がらない一方で、rdが平均値の場合、プロモーションによって売上が伸びることが伺える。これをまとめると、品質が平均的ならプロモーションで売上は上がるが、プロモーションが平均的で品質投資をしても売上に逆効果となることが伺える。R&amp;D投資による負の効果については価格との関係もあるかもしれない。品質が向上すると通常価格も上がるため、プロモーションがあまり高くない状態においては、価格の向上によって売上を損ねるかもしれない。この点については、価格も含めたさらなる調査、分析が必要になる。</p>
<p>量的変数同士の交差項分析結果の図示化においては、二種類の方法がある。一つ目は調整変数として捉える変数を高水準（例、平均 <span class="math inline">\(+\)</span> 1標準偏差）と低水準（例、平均 <span class="math inline">\(-\)</span> 1標準偏差）に二分し、前節の傾きダミーの図示化のようにそれぞれの場合でメイン変数による被説明変数への傾きを描画する方法である。これは、前節で使用した<code>sjPlot</code>パッケージで実行できる。 二つ目は、メインの変数が被説明変数へ与える影響を縦軸に、調整変数の値を横軸に取ることによって、メイン変数が持つ効果が調整変数によって変化する様子を連続的に描画する方法である。これは、<code>marginaleffects</code>というパッケージを用いる。</p>
<p>まず、一つ目の方法は、以下の通り実行することができる。分析の結果、やはりプロモーション水準が低い場合にはR&amp;D投資が売上に与える影響は負であるものの、プロモーション水準が高い場合には正に転じることが伺える。</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="交差項.html#cb221-1" tabindex="-1"></a>leg <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Mean - 1sd&quot;</span>, <span class="st">&quot;Mean&quot;</span>, <span class="st">&quot;Mean + 1sd&quot;</span>)</span>
<span id="cb221-2"><a href="交差項.html#cb221-2" tabindex="-1"></a>int_fig1 <span class="ot">&lt;-</span> <span class="fu">plot_model</span>(fit_int_c, <span class="at">type =</span> <span class="st">&quot;int&quot;</span>, <span class="at">mdrt.values =</span> <span class="st">&quot;meansd&quot;</span>, <span class="at">ci.lvl =</span> .<span class="dv">9999999999</span>) <span class="sc">+</span></span>
<span id="cb221-3"><a href="交差項.html#cb221-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Predicted values of Sales (R&amp;D * Promotion)&quot;</span>,</span>
<span id="cb221-4"><a href="交差項.html#cb221-4" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;R&amp;D Investment&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Sales&quot;</span>)<span class="sc">+</span> </span>
<span id="cb221-5"><a href="交差項.html#cb221-5" tabindex="-1"></a>  <span class="fu">scale_color_discrete</span>(<span class="at">name =</span> <span class="st">&quot;Promotion level&quot;</span>, <span class="at">labels=</span>leg)</span></code></pre></div>
<pre><code>## Scale for colour is already present.
## Adding another scale for colour, which will replace the existing scale.</code></pre>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="交差項.html#cb223-1" tabindex="-1"></a>int_fig1</span></code></pre></div>
<p><img src="mktres_lecture_files/figure-html/slopeHeadphone-1.png" width="672" /></p>
<p>続いて、二つ目の方法を実行するために、以下の要領でパッケージをインストールしてほしい。<code>marginaleffects</code> は、<code>margins</code> や <code>emtrends</code> の機能を引き継ぎ、限界効果に関する計算結果を図示化するためのパッケージである<a href="#fn13" class="footnote-ref" id="fnref13"><sup>13</sup></a>。</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="交差項.html#cb224-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;marginaleffects&quot;</span>)</span></code></pre></div>
<p>R&amp;D が 売上に与える影響（傾き）がどのように変化するかは、<code>plot_slopes()</code> という関数を用いる。以下は、傾きの変化に関する図の出力結果である。</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="交差項.html#cb225-1" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb225-2"><a href="交差項.html#cb225-2" tabindex="-1"></a>int_fig2 <span class="ot">&lt;-</span> <span class="fu">plot_slopes</span>(fit_int_c, <span class="at">variables =</span> <span class="st">&quot;rd_c&quot;</span>, <span class="at">condition =</span> <span class="st">&quot;promotion_c&quot;</span>, <span class="at">conf_level =</span> .<span class="dv">99999999</span>) <span class="sc">+</span></span>
<span id="cb225-3"><a href="交差項.html#cb225-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Marginal effects of R&amp;D on Sales&quot;</span>,</span>
<span id="cb225-4"><a href="交差項.html#cb225-4" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Promotion&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Slope of R&amp;D on Sales&quot;</span>) <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="fu">aes</span>(<span class="at">yintercept=</span><span class="dv">0</span>), <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) </span>
<span id="cb225-5"><a href="交差項.html#cb225-5" tabindex="-1"></a>int_fig2</span></code></pre></div>
<p><img src="mktres_lecture_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>分析の結果、promotionが0（平均）である条件を基準に、R&amp;Dの傾きが正に転じていることが伺える。なお、よく見ると、直線の周りに灰色の影が描画されていることがわかる。これは、99%信頼区間を示している。今回は人工的に作成したデータなので、非常に当てはまりがよく信頼区間がとても狭くなっているが、実際のデータを用いて同様の図示化をすればもう少し明確に信頼区間を視認できる。このように、交差項を利用した回帰モデルを分析する際は、事後的な図示化を行うことを心がけると良い。この作業により実務的・学術的により有益な含意につながることがある。</p>
<!--- fit1_ame <- slopes(fit_int_c, variables = "rd_c",
                   newdata = datagrid(promotion_c = -86:155))--->
<p>以下は、<code>plot_slopes()</code> に関するおまけである。図示化の確認のために、firmdata19を使って、マーケティング支出と総資産との交差項により、利益率を説明する回帰モデルを考える。以下では、中心化と回帰分析の実行、図の出力を実施している（回帰分析結果は省略）。</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="交差項.html#cb226-1" tabindex="-1"></a>firmdata19 <span class="ot">&lt;-</span> firmdata19 <span class="sc">%&gt;%</span> </span>
<span id="cb226-2"><a href="交差項.html#cb226-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mkexp_c =</span> mkexp <span class="sc">-</span> <span class="fu">mean</span>(mkexp),</span>
<span id="cb226-3"><a href="交差項.html#cb226-3" tabindex="-1"></a>         <span class="at">asset_c =</span> total_assets <span class="sc">-</span> <span class="fu">mean</span>(total_assets))</span>
<span id="cb226-4"><a href="交差項.html#cb226-4" tabindex="-1"></a></span>
<span id="cb226-5"><a href="交差項.html#cb226-5" tabindex="-1"></a>fit_int2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(op <span class="sc">~</span>  mkexp_c <span class="sc">*</span> asset_c, <span class="at">data =</span> firmdata19)</span>
<span id="cb226-6"><a href="交差項.html#cb226-6" tabindex="-1"></a></span>
<span id="cb226-7"><a href="交差項.html#cb226-7" tabindex="-1"></a>int_fig3 <span class="ot">&lt;-</span> <span class="fu">plot_slopes</span>(fit_int2, <span class="at">variables =</span> <span class="st">&quot;mkexp_c&quot;</span>, <span class="at">condition =</span> <span class="st">&quot;asset_c&quot;</span>, <span class="at">conf_level =</span> <span class="fl">0.99</span>) <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="fu">aes</span>(<span class="at">yintercept=</span><span class="dv">0</span>), <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) </span>
<span id="cb226-8"><a href="交差項.html#cb226-8" tabindex="-1"></a>int_fig3</span></code></pre></div>
<p><img src="mktres_lecture_files/figure-html/omake-1.png" width="672" /></p>
<p>図を見ると、Headphoneデータよりもはっきりと信頼区間が視認できる。マーケティング支出の効果は資産によって低下するように見えるが、信頼区間を考慮すると、資産額が平均値（asset_c <span class="math inline">\(=0\)</span>）付近の値を取るときのみマーケティング支出は負に有意の影響を持つが、それ以外の区間では有意でない（信頼区間に0を含む）ことが伺える。このように、信頼区間の出力は結果の解釈を有意義なものにしてくれる。</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="12">
<li id="fn12"><p>試しに、<code>plot_model</code> 内の信頼区間に関する引数を <code>ci.lvl = NA</code>とし、実線のみの比較を確認して見て欲しい<a href="交差項.html#fnref12" class="footnote-back">↩︎</a></p></li>
<li id="fn13"><p>本講義では、詳細は割愛するが以下から詳細を確認できる <a href="https://vincentarelbundock.github.io/marginaleffects/dev/" class="uri">https://vincentarelbundock.github.io/marginaleffects/dev/</a><a href="交差項.html#fnref13" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ダミー変数.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="係数比較.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/08-reg2.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
